// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/roommate-login/Fresh.tsx": () => import("../components/mockups/roommate-login/Fresh.tsx"),
  "./components/mockups/roommate-login/Midnight.tsx": () => import("../components/mockups/roommate-login/Midnight.tsx"),
  "./components/mockups/roommate-login/Warm.tsx": () => import("../components/mockups/roommate-login/Warm.tsx")
};
